### ISSUE TITLE
Dataset higpt_stage1 is unavailable

### ISSUE THREAD

**Issue by ronpay** [HKUDS/HiGPT#2]
Hello,

I attempted to download the dataset by executing `wget https://archive.org/download/higpt_stage1/matching_instruction.tar.gz` but encountered a 404 error as the link seems to be broken. 

Could you please update the link or provide an alternative method for downloading the dataset?

Thank you for your assistance!

**Comment by tjb-tech** [comment]
> Hello,
> 
> I attempted to download the dataset by executing `wget https://archive.org/download/higpt_stage1/matching_instruction.tar.gz` but encountered a 404 error as the link seems to be broken.
> 
> Could you please update the link or provide an alternative method for downloading the dataset?
> 
> Thank you for your assistance!

Thanks for your questions! Because the size of training data in stage 1 is too large (26 + G), so the upload process to archive always failed. I will find some other methods to upload the stage 1 data to archive. A possible alternative method is to use baidu cloud in the link https://pan.baidu.com/s/1rtdxzhRRcEUEpXoWKml36A?pwd=id6u . Please first use it and feel free to comment if you have some difficulties in downloading the data.
